begin;

-- Corrige nomes populares com perda de acentos no catalogo de especies.
update public.species set common_name = 'acácia-auriculiforme' where scientific_name = 'Acacia auriculiformis'; -- ac?cia-auriculiforme
update public.species set common_name = 'acácia-mangium' where scientific_name = 'Acacia mangium'; -- ac?cia-mangium
update public.species set common_name = 'macaúba' where scientific_name = 'Acrocomia aculeata'; -- maca?ba
update public.species set common_name = 'tapiá' where scientific_name = 'Alchornea glandulosa'; -- tapi?
update public.species set common_name = 'biribá' where scientific_name = 'Annona mucosa'; -- birib?
update public.species set common_name = 'gonçalo-alves' where scientific_name = 'Astronium graveolens'; -- gon?alo-alves
update public.species set common_name = 'sol-da-bolívia' where scientific_name = 'Brownea grandiceps'; -- sol-da-bol?via
update public.species set common_name = 'jequitibá-branco' where scientific_name = 'Cariniana estrellensis'; -- jequitib?-branco
update public.species set common_name = 'jequitibá-açu' where scientific_name = 'Cariniana ianeirensis'; -- jequitib?-a?u
update public.species set common_name = 'jequitibá' where scientific_name = 'Cariniana legalis'; -- jequitib?
update public.species set common_name = 'canafístula' where scientific_name = 'Cassia ferruginea'; -- canaf?stula
update public.species set common_name = 'cássia-rosa' where scientific_name = 'Cassia grandis'; -- c?ssia-rosa
update public.species set common_name = 'embaúba' where scientific_name = 'Cecropia glaziovii'; -- emba?ba
update public.species set common_name = 'embaúba-branca' where scientific_name = 'Cecropia hololeuca'; -- emba?ba-branca
update public.species set common_name = 'araribá-rosa' where scientific_name = 'Centrolobium robustum'; -- ararib?-rosa
update public.species set common_name = 'araribá-amarelo' where scientific_name = 'Centrolobium tomentosum'; -- ararib?-amarelo
update public.species set common_name = 'tarumã' where scientific_name = 'Citharexylum myrianthum'; -- tarum?
update public.species set common_name = 'clúsia' where scientific_name = 'Clusia fluminensis'; -- cl?sia
update public.species set common_name = 'abricó-de-macaco' where scientific_name = 'Couroupita guianensis'; -- abric?-de-macaco
update public.species set common_name = 'cambboatá' where scientific_name = 'Cupania emarginata'; -- cambboat?
update public.species set common_name = 'ipê-verde' where scientific_name = 'Cybistax antisyphilitica'; -- ip?-verde
update public.species set common_name = 'jacarandá-da-bahia' where scientific_name = 'Dalbergia nigra'; -- jacarand?-da-bahia
update public.species set common_name = 'suinã' where scientific_name = 'Erythrina speciosa'; -- suin?
update public.species set common_name = 'açaizeiro' where scientific_name = 'Euterpe oleracea'; -- a?aizeiro
update public.species set common_name = 'ficus-elástica' where scientific_name = 'Ficus elastica'; -- ficus-el?stica
update public.species set common_name = 'ipê-dourado' where scientific_name = 'Handroanthus chrysotrichus'; -- ip?-dourado
update public.species set common_name = 'ipê-roxo' where scientific_name = 'Handroanthus heptaphyllus'; -- ip?-roxo
update public.species set common_name = 'ipê-amarelo' where scientific_name = 'Handroanthus serratifolius'; -- ip?-amarelo
update public.species set common_name = 'ipê-da-várzea' where scientific_name = 'Handroanthus umbellatus'; -- ip?-da-v?rzea
update public.species set common_name = 'ingá-cipó' where scientific_name = 'Inga edulis'; -- ing?-cip?
update public.species set common_name = 'ingá' where scientific_name = 'Inga laurina'; -- ing?
update public.species set common_name = 'abricó-da-praia' where scientific_name = 'Labramia bojeri'; -- abric?-da-praia
update public.species set common_name = 'açoita-cavalo' where scientific_name = 'Luehea divaricata'; -- a?oita-cavalo
update public.species set common_name = 'açoita-cavalo' where scientific_name = 'Luehea grandiflora'; -- a?oita-cavalo
update public.species set common_name = 'jacarandá-violeta' where scientific_name = 'Machaerium brasiliense'; -- jacarand?-violeta
update public.species set common_name = 'jacarandá-ferro' where scientific_name = 'Machaerium scleroxylon'; -- jacarand?-ferro
update public.species set common_name = 'maricá' where scientific_name = 'Mimosa bimucronata'; -- maric?
update public.species set common_name = 'sabiá' where scientific_name = 'Mimosa caesalpiniifolia'; -- sabi?
update public.species set common_name = 'cambará' where scientific_name = 'Moquiniastrum polymorphum'; -- cambar?
update public.species set common_name = 'castanha-do-maranhão' where scientific_name = 'Pachira glabra'; -- castanha-do-maranh?o
update public.species set common_name = 'cebolão' where scientific_name = 'Phytolacca dioica'; -- cebol?o
update public.species set common_name = 'pau-jacaré' where scientific_name = 'Piptadenia gonoacantha'; -- pau-jacar?
update public.species set common_name = 'vinhático' where scientific_name = 'Plathymenia reticulata'; -- vinh?tico
update public.species set common_name = 'jacarandá-branco' where scientific_name = 'Platypodium elegans'; -- jacarand?-branco
update public.species set common_name = 'cambucá' where scientific_name = 'Plinia edulis'; -- cambuc?
update public.species set common_name = 'embiruçu' where scientific_name = 'Pseudobombax grandiflorum'; -- embiru?u
update public.species set common_name = 'araçá-da-praia' where scientific_name = 'Psidium cattleianum'; -- ara??-da-praia
update public.species set common_name = 'araçá' where scientific_name = 'Psidium guineense'; -- ara??
update public.species set common_name = 'sabão-de-soldado' where scientific_name = 'Sapindus saponaria'; -- sab?o-de-soldado
update public.species set common_name = 'cássia-do-nordeste' where scientific_name = 'Senna spectabilis'; -- c?ssia-do-nordeste
update public.species set common_name = 'espatódea' where scientific_name = 'Spathodea campanulata'; -- espat?dea
update public.species set common_name = 'cajá-manga' where scientific_name = 'Spondias dulcis'; -- caj?-manga
update public.species set common_name = 'cajá' where scientific_name = 'Spondias mombin'; -- caj?
update public.species set common_name = 'chichá' where scientific_name = 'Sterculia apetala'; -- chich?
update public.species set common_name = 'jamelão' where scientific_name = 'Syzygium cumini'; -- jamel?o
update public.species set common_name = 'ipê-branco' where scientific_name = 'Tabebuia roseoalba'; -- ip?-branco
update public.species set common_name = 'algodão-da-praia' where scientific_name = 'Talipariti pernambucense'; -- algod?o-da-praia
update public.species set common_name = 'ipê-de-jardim' where scientific_name = 'Tecoma stans'; -- ip?-de-jardim
update public.species set common_name = 'chapéu-de-sol' where scientific_name = 'Terminalia mantaly'; -- chap?u-de-sol
update public.species set common_name = 'chapéu-de-napoleão' where scientific_name = 'Thevetia peruviana'; -- chap?u-de-napole?o
update public.species set common_name = 'catinguá' where scientific_name = 'Trichilia hirta'; -- catingu?
update public.species set common_name = 'acácia-seyal' where scientific_name = 'Vachellia seyal'; -- ac?cia-seyal
update public.species set common_name = 'ipê-felpudo' where scientific_name = 'Zeyheria tuberculosa'; -- ip?-felpudo

commit;
